#!/bin/bash
userresources=$HOME/.Xresources
usermodmap=$HOME/.xmodmaprc
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

	xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

	xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

envfile="$HOME/.gnupg/gpg-agent.env"
if [[ -e "$envfile" ]] && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
	eval "$(cat "$envfile")"
else
	eval "$(gpg-agent --daemon --enable-ssh-support )"
fi
export GPG_AGENT_INFO  # the env file does not contain the export statement
export SSH_AUTH_SOCK   # enable gpg-agent for ssh

if [ -z "$(pgrep urxvtd)" ] ; then
	urxvtd -q -o -f &
fi

#if [ -z "$(pgrep compton)" ] ; then
#	compton -cCG \
#		--vsync opengl \
#		--config .dotfiles/compton/compton.conf &
#fi

if [ -z "$(pgrep xbindkeys)" ] ; then
	xbindkeys &
fi

if [ -z "$(pgrep fehchanger)" ] ; then
	.dotfiles/i3/fehchanger &
fi

if [ -z "$(pgrep xsettingsd)" ] ; then
	xsettingsd &
fi
#exec i3
