export DOTFILES="$HOME/.dotfiles"
export TMPDIR="$HOME/tmp"
export BROWSER=google-chrome-stable
export TERM=xterm-256color
export TERM=rxvt-unicode-256color
export VIMRUNTIME="/usr/local/share/vim/vim74"
export PAGER="/usr/local/bin/vimpager"
export JAVA_HOME="/usr/lib/jvm/java-8-jdk"


