# Environment Variables
export EDITOR=vim
export TERM=xterm-256color
ZSHCONFDIR=($DOTFILES/zsh)
# export PATH="$HOME/bin:$PATH"
typeset -gU path
path=($HOME/bin $HOME/.gem/ruby/2.2.0/bin $path)

# Autoload

# Completion and other built-in functions
autoload -Uz compinit vcs_info
compinit


fpath=( $ZSHCONFDIR/functions "${fpath[@]}")
#autoload -Uz ww _git-add vcs_info_rprompt dot 
for file in $ZSHCONFDIR/functions/* ; do
	if [[ -a "$file" ]]; then
		filename=${file:t}
		autoload -Uz "$filename"
	fi
done


# Source Files
# Add files to "sourcefiles" array, then source each file in the array.
typeset -ga sourcefiles

for file in $ZSHCONFDIR/aliases/* ; do
	if [[ -a "$file" ]]; then
		sourcefiles+="$file"
	fi
done

# Prompt Specific
sourcefiles+="$ZSHCONFDIR/prompt/prompt.zsh"

for file in $sourcefiles[@]; do
	if [[ -a "$file" ]]; then
		source "$file"
	fi
done
